# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  zramSwap.enable = true;

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_6_8;
  boot.kernelParams = [
    "intel_iommu=on"
    "iommu=pt"
    "vfio-pci"
#    "i915.force_probe=!7d55"
#    "xe.force_probe=7d55"
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;

  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      intel-vaapi-driver
      libvdpau-va-gl
      vaapiIntel
      vaapiVdpau
    ];
  };


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/27e6907b-d25a-4b84-80f5-f9d900eb13eb";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b0395b07-7632-43ad-956b-0cdb3a88edfc".device = "/dev/disk/by-uuid/b0395b07-7632-43ad-956b-0cdb3a88edfc";

  fileSystems."/boot" = { device = "/dev/disk/by-uuid/F553-A9F7";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/home/sebastorama/.cache/kwin" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "size=10M" "mode=777" ];
  };

  fileSystems."/home/sebastorama/.cache/plasmashell" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "size=10M" "mode=777" ];
  };

  fileSystems."/home/sebastorama/.cache/mesa_shader_cache" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "size=10M" "mode=777" ];
  };

  fileSystems."/home/sebastorama/.cache/kscreen_osd_service" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "size=10M" "mode=777" ];
  };


  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
